import {mapScene,visitedScene} from '../scenePresentation';
import {pulpColors} from '../theme';
import React from 'react';
import {View,Text,ScrollView,Pressable} from 'react-native';
import type {Command,GameState} from '../../src/core/types';
import {getChapter} from '../../src/core/story/chapters';
import {loadSeenChapters,markChapterSeen} from '../../src/core/storage';
import {QuietButton} from './QuietChrome';
import SceneArrival from './SceneArrival';
import {artSource} from './Art';
import {font,palette} from '../theme';
import {useScreenPadding} from '../useScreenPadding';
export default function ChapterView({state,dispatch}:{state:GameState;dispatch:(c:Command)=>void}){const pad=useScreenPadding();const active=state.chapter;const chapter=active?getChapter(active.id):undefined;const [seen,setSeen]=React.useState(false);React.useEffect(()=>{let alive=true;setSeen(false);if(active)loadSeenChapters().then(s=>{if(alive)setSeen(s.includes(active.id))}).catch(()=>{});return()=>{alive=false}},[active?.id]);if(!active||!chapter)return null;const atEnd=seen||active.paragraph>=chapter.text.length-1;const close=()=>{void markChapterSeen(active.id);dispatch({type:'SkipChapter'})};return <SceneArrival source={chapter.id.includes('_open')||chapter.id.startsWith('prologue_')||chapter.id==='ending_lose'?require('../../assets/scence/headless-sleepers.jpg'):chapter.id.includes('_ending')||chapter.id==='run_ending'||chapter.id==='run_true_ending'||chapter.id==='ending_win'||chapter.id==='ending_secret'||chapter.id==='episode_end'?require('../../assets/scence/heads-returned-dawn.jpg'):chapter.id.includes('_gate')||chapter.id==='before_final_boss'?mapScene(state).source:chapter.id==='secret_unlocked'||chapter.id==='run_ultimate_gate'?require('../../assets/scence/journey/thai-v24/16-secret-throne.jpg'):visitedScene(state).source} sceneKey={chapter.id}><View style={{flex:1,paddingTop:pad.top+16,paddingHorizontal:24,paddingBottom:pad.bottom+20,justifyContent:'flex-end',backgroundColor:pulpColors.storySceneShade}}><View style={{maxHeight:'68%',backgroundColor:pulpColors.storyTextShade,padding:18,gap:12}}><Text style={{fontFamily:font.display,color:palette.moon,fontSize:25}}>{state.campaign?`คืนที่ ${state.campaign.night} · `:''}{chapter.title}</Text><Pressable onPress={()=>atEnd?close():dispatch({type:'AdvanceChapter'})}><ScrollView style={{maxHeight:290}}><Text style={{fontFamily:font.body,color:palette.text,fontSize:25,lineHeight:32}}>{seen?chapter.text.join('\n\n'):chapter.text[active.paragraph]}</Text></ScrollView></Pressable><Text style={{fontFamily:font.ui,color:palette.textDim,fontSize:11}}>{seen?'เคยอ่านแล้ว':`${active.paragraph+1}/${chapter.text.length}`}</Text><QuietButton label={atEnd?'เดินทางต่อ':'อ่านต่อ'} primary onPress={()=>atEnd?close():dispatch({type:'AdvanceChapter'})}/>{!atEnd&&<QuietButton label="ข้ามบทนี้" onPress={close}/>}</View></View></SceneArrival>;}
