/** Distinct art for the chapter pilot cards; upgrades keep their original identity. */
export const CARD_ART_SOURCES: Record<string, import('react-native').ImageSourcePropType> = {
  'phase_strike': require('../assets/monsters/phi-pop.png'),
  'ghost_wail': require('../assets/monsters/phi-pop.png'),
  'floating_dodge': require('../assets/monsters/phi-pop.png'),
  'cursed_touch': require('../assets/monsters/nang-tanee.png'),
  'death_wail': require('../assets/monsters/nang-tanee.png'),
  'guard': require('../assets/monsters/nang-tanee.png'),
  'krasue_claw': require('../assets/monsters/phi-krasue-pulp.png'),
  'night_hunt': require('../assets/monsters/phi-krasue-pulp.png'),
  'krasue_guard': require('../assets/monsters/phi-krasue-pulp.png'),
  'graceful_strike': require('../assets/monsters/phi-nang-ram.png'),
  'brace': require('../assets/monsters/phi-nang-ram.png'),
  'phantom_slash': require('../assets/monsters/phi-pong-kang.png'),
  'swipe': require('../assets/monsters/phi-pong-kang.png'),
  'maul': require('../assets/monsters/phi-pong-kang.png'),
  'ward_riposte': require('../assets/cards/ward_riposte.webp'),
  'last_stand_cut': require('../assets/cards/last_stand_cut.webp'),
  'threefold_strike': require('../assets/cards/threefold_strike.webp'),
  'spirit_pact': require('../assets/cards/spirit_pact.webp'),
  'poison_echo': require('../assets/cards/poison_echo.webp'),
  'ancestor_council': require('../assets/cards/ancestor_council.webp'),
  'whisper_ear': require('../assets/cards/whisper_ear-v2.webp'),
  'yantra_cloth': require('../assets/cards/yantra_cloth-v2.webp'),
  'invite_spirit': require('../assets/cards/invite_spirit-v2.webp'),
  'set_altar': require('../assets/cards/set_altar-v2.webp'),
  'phrai_oil': require('../assets/cards/phrai_oil-v2.webp'),
  'pop_feast': require('../assets/cards/pop_feast-v2.webp'),
  'tanee_roots': require('../assets/cards/tanee_roots-v2.webp'),
  'krasue_venom': require('../assets/cards/krasue_venom-v2.webp'),
  'dancer_steps': require('../assets/cards/dancer_steps-v2.webp'),
  'pong_fury': require('../assets/cards/pong_fury-v2.webp'),
};
