// Web-only visual review harness. Normal exports show no fixtures or review controls.
import React from 'react';
import {Platform,Text,View} from 'react-native';
import {useLocalSearchParams} from 'expo-router';
import type {Command,GameState} from '../src/core/types';
import type {RNG} from '../src/core/rng';
import {applyCommand} from '../src/core/reducer';
import DefeatOverlay from './components/battle/DefeatOverlay';
import ShopView from './components/ShopView';
import StoryEventView from './components/StoryEventView';
import ChapterView from './components/ChapterView';
import RunCompleteScreen from './components/RunCompleteScreen';
import LevelUpOverlay from './components/battle/LevelUpOverlay';
import CardRewardOverlay from './components/battle/CardRewardOverlay';
import DeckView from './components/DeckView';
import BlessingView from './components/BlessingView';
import {QuietButton,QuietPage} from './components/QuietChrome';
import {useAppFonts} from './useAppFonts';
import StatusStrip from './components/battle/StatusStrip';
import MinionRow from './components/battle/MinionRow';
import BlessingSeals from './components/battle/BlessingSeals';
import ComboBook from './components/battle/ComboBook';
import MonsterArea from './components/battle/MonsterArea';
import EnemyHandCard from './components/battle/EnemyHandCard';
import RestDestinations from './components/RestDestinations';
import SceneGhostChoices from './components/SceneGhostChoices';
import AdventureChoices from './components/AdventureChoices';
import PlayerHand from './components/battle/PlayerHand';
import PlayerHUD from './components/battle/PlayerHUD';
import {skippableSlots} from '../src/core/map/adventure';
import {describeOffer} from './components/offerDisplay';
import {palette,font} from './theme';
import ArchiveView from './components/ArchiveView';
import {emptyArchive,mergeDiscovery} from '../src/core/archive/progress';
export default function UiReview(){
 const {screen}=useLocalSearchParams<{screen:string}>();const [loaded]=useAppFonts();
 const [state,setState]=React.useState<GameState|null>(null),[error,setError]=React.useState(''),[done,setDone]=React.useState(false);
 const [routeSelected,setRouteSelected]=React.useState<number|null>(null);
 const rng=React.useRef<RNG>({s:0});
 const enabled=Platform.OS==='web'&&process.env.EXPO_PUBLIC_UI_REVIEW==='1';
 React.useEffect(()=>{if(!enabled)return;let alive=true;fetch('/ui-review-fixtures.json').then(r=>{if(!r.ok)throw Error('Review fixtures unavailable');return r.json();}).then(data=>{const f=data.fixtures[screen];if(!f)throw Error('Unknown review screen');if(alive){rng.current=f.rng;setState(f.state);}}).catch(e=>{if(alive)setError(String(e));});return()=>{alive=false};},[screen,enabled]);
 const dispatch=(cmd:Command)=>{if(!state)return;const out=applyCommand(state,cmd,rng.current);rng.current=out.rng;setState(out.state);};
 if(!enabled)return <QuietPage title="หน้าตรวจภาพ" subtitle="เปิดเฉพาะชุดตรวจภาพเวอร์ชันเว็บ"><Text style={{color:palette.text}}>กลับไปเล่นเกมจากหน้าแรก</Text></QuietPage>;
 if(error)return <Text accessibilityRole="alert">{error}</Text>;
 if(!loaded||!state)return <Text>กำลังเปิดภาพจากเกม…</Text>;
 if(done)return <QuietPage title="ดำเนินการแล้ว"><Text style={{color:palette.text}}>ปุ่มตอบสนองแล้ว</Text></QuietPage>;
 const telemetry=<Text pointerEvents="none" testID="qa-state" style={{position:'absolute',opacity:0,width:1,height:1}}>{JSON.stringify({gold:state.player.gold,deck:state.masterDeck.map(c=>[c.id,c.upgradeLevel??0]),stock:state.shopStock?.length,phase:state.phase,hp:state.player.maxHp,enemyHp:state.enemy?.hp,hand:state.piles.hand.map(c=>c.id),plays:state.runMetrics?.cardsPlayed,adventure:state.pages?.adventure})}</Text>;
 const wrap=(child:React.ReactNode)=><View style={{flex:1}}>{child}{telemetry}</View>;
 if(screen?.startsWith('archive-'))return wrap(<ArchiveView fixture={screen==='archive-empty'?emptyArchive():state.discovery?mergeDiscovery(emptyArchive(),state.discovery):emptyArchive()} onClose={()=>setDone(true)}/>);
 if(screen?.startsWith('adventure-'))return wrap(state.phase==='map'?<AdventureChoices offers={state.pages!.current!.offers} resolved={state.pages!.current!.resolved} slotIds={state.pages!.adventure!.slotIds} onEnter={(_,index)=>dispatch({type:'ChooseOffer',index})} onSkip={()=>dispatch({type:'Proceed'})} skipCount={skippableSlots(state).length}/>:<ShopView state={state} dispatch={dispatch}/>);
 if(screen==='hand')return wrap(<View style={{flex:1}}><MonsterArea monsterId={state.enemy!.id} enemy={state.enemy}/><PlayerHand state={state} cards={state.piles.hand} energy={state.player.energy} playedCardIds={[]} hoveredCardId={null} onHoverChange={()=>{}} onPlayCard={(_,index)=>dispatch({type:'PlayCard',index})}/><PlayerHUD classId={state.classId} hp={state.player.hp} maxHp={state.player.maxHp} energy={state.player.energy} maxEnergy={state.player.maxEnergy} block={state.player.block} maxHandSize={state.player.maxHandSize} drawCount={state.piles.draw.length} onEndTurn={()=>dispatch({type:'EndTurn'})} blessings={<BlessingSeals blessings={state.blessings}/>} statuses={<StatusStrip effects={state.player.statusEffects}/>} helpers={<MinionRow compact minions={state.minions} owner="player"/>}/></View>);
 if(screen==='rest-cards')return wrap(<RestDestinations offers={[{kind:'shop_card'},{kind:'shop_remove'},{kind:'shop_upgrade'}] as any} resolved={[]} onEnter={()=>setDone(true)}/>);
 if(screen?.startsWith('rest-'))return wrap(state.phase==='map'?<SceneGhostChoices choices={[{display:describeOffer(state.pages!.current!.offers[0],0),resolved:!!state.pages!.current!.resolved[0],index:0}]} selected={routeSelected} onSelect={setRouteSelected} onEnter={index=>dispatch({type:'ChooseOffer',index})}/>:state.phase==='event'?<StoryEventView state={state} dispatch={dispatch}/>:<ShopView state={state} dispatch={dispatch}/>);
 if(screen==='status')return wrap(<QuietPage title="สถานะ"><StatusStrip effects={state.player.statusEffects}/><MinionRow compact owner="player" minions={state.minions}/></QuietPage>);
 if(screen==='blessing-seals')return wrap(<QuietPage title="พร"><BlessingSeals blessings={state.blessings}/></QuietPage>);
 if(screen==='combo-book')return wrap(<ComboBook state={state} visible={!done} onClose={()=>setDone(true)}/>);
 if(screen==='enemy-card'||screen==='enemy-card-multi')return wrap(<View style={{flex:1}}><MonsterArea monsterId={state.enemy?.id??'phi-pop'} enemy={state.enemy} enemies={screen==='enemy-card-multi'?[{...state.enemy!,id:'phi-pop'},{...state.enemy!,id:'phi-krasue'}]:undefined}/><EnemyHandCard ownerId={screen==='enemy-card-multi'?'phi-krasue':state.enemy?.id} card={{id:'pop_strike',name:'ข่วนกรงเล็บ',damage:8,block:0,cost:1}} playing ownerIndex={screen==='enemy-card-multi'?1:0} ownerCount={screen==='enemy-card-multi'?2:1} delay={0} cardIndex={0} totalCards={1}/></View>);
 if(screen==='defeat')return <DefeatOverlay onHome={()=>setDone(true)}/>;
 if(screen==='summary'||screen==='summary-defeat')return <RunCompleteScreen state={state} onNewRun={()=>setDone(true)} onMainMenu={()=>setDone(true)} onJournal={()=>setDone(true)}/>;
 if(screen==='chapter')return <ChapterView state={state} dispatch={dispatch}/>;
 if(screen==='event'||screen==='event-result')return wrap(state.phase==='event'?<StoryEventView state={state} dispatch={dispatch}/>:<QuietPage title="กลับจุดพักแล้ว"><Text style={{color:palette.text}}>ดำเนินการแล้ว</Text></QuietPage>);
 if(screen==='levelup'||screen==='levelup-blessing')return wrap(state.phase==='levelup'?<LevelUpOverlay state={state} playerLevel={state.player.level} onChoose={(option,index)=>dispatch({type:'ChooseLevelUpOption',option,index})} onSkip={()=>dispatch({type:'SkipLevelUp'})}/>:<QuietPage title="รับวิชาแล้ว"><Text style={{color:palette.text}}>ดำเนินการแล้ว</Text></QuietPage>);
 if(screen==='reward')return state.phase==='reward'?<CardRewardOverlay choices={state.cardReward?.choices??[]} deck={state.masterDeck} onChoose={index=>dispatch({type:'ChooseCardReward',index})} onSkip={()=>dispatch({type:'SkipCardReward'})}/>:<QuietPage title="เลือกรางวัลแล้ว"><Text style={{color:palette.text}}>ดำเนินการแล้ว</Text></QuietPage>;
 if(screen==='deck')return <DeckView state={{...state,deckOpen:true}} dispatch={cmd=>cmd.type==='CloseDeck'?setDone(true):dispatch(cmd)}/>;
 if(screen==='blessings')return <BlessingView blessings={state.blessings} onClose={()=>setDone(true)}/>;
 return wrap(<View style={{flex:1,backgroundColor:palette.ink}}>{state.phase==='shop'?<ShopView state={state} dispatch={dispatch}/>:<QuietPage title="กลับจุดพักแล้ว"><QuietButton label="ดำเนินการแล้ว"/></QuietPage>}</View>);
}
